name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv
          # Activate virtual environment using a compatible shell command
          . venv/bin/activate
          # Verify that activation worked
          which python
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          which python
          pip install -r requirements.txt

      - name: Run tests
        run: |
          . venv/bin/activate
          which python
          pytest

  dockerize:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dockerize the application
        run: |
          docker build -t flask-app .
          docker-compose up -d

  deploy:
    runs-on: ubuntu-latest
    needs: dockerize

    steps:
      - name: Simulate deployment
        run: echo "Deployment simulation complete."
