name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv
          # Activate virtual environment
          source ./venv/bin/activate
          # Check if Python is correctly using the virtual environment
          python --version
          which python
          pip install -r requirements.txt
        shell: bash

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv
          source ./venv/bin/activate
          python --version
          which python
          pip install -r requirements.txt
        shell: bash

      - name: Run tests
        run: |
          source ./venv/bin/activate
          python --version
          which python
          pytest
        shell: bash

  dockerize:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dockerize the application
        run: |
          docker build -t flask-app .
          docker-compose up -d
        shell: bash

  deploy:
    runs-on: ubuntu-latest
    needs: dockerize

    steps:
      - name: Simulate deployment
        run: echo "Deployment simulation complete."
